---
- hosts: localhost
  name: Setup Postgres Repositories
  become: yes
  gather_facts: yes
  vars_files:
    - group_vars/vars.yaml

  collections:
    - edb_devops.edb_postgres

  roles:
    - setup_repo
    - install_dbserver

  pre_tasks:
    - name: Initialize the user defined variables
      set_fact:
        pg_version: "{{ version }}"
        pg_type: "{{ type }}"
        repo_username: "{{ username }}"
        repo_password: "{{ password }}"
